export enum MutationTypes
{
//  ui
	CLEAR_UI = 'CLEAR_UI',

	//  header

	//  game

	//  device
	IS_SM_UPDATED = 'IS_SM_UPDATED',
	IS_MD_UPDATED = 'IS_MD_UPDATED',
	IS_LG_UPDATED = 'IS_LG_UPDATED',
	IS_XL_UPDATED = 'IS_XL_UPDATED',
	IS_PORTRAIT = 'IS_PORTRAIT',
	IS_LANDSCAPE = 'IS_LANDSCAPE',
	DEVICE_UPDATED = 'DEVICE_UPDATED',
	URL_PARAMS_UPDATED = 'URL_PARAMS_UPDATED',
}
